### PR TITLE
chore: use new unittest.mock from standard library

### PR DESCRIPTION
**Pull request by a-detiste**
https://github.com/testing-cabal/mock

"mock is now part of the Python standard library, available as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards."

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x I have read the [Contribution Guidelines](https://github.com/twilio/twilio-python/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

### CODE REVIEW

**Comment by tiwarishubham635** [comment]
I see some error [here](https://github.com/twilio/twilio-python/actions/runs/8558651272/job/23453658266#step:6:33), can you check this?

**Comment by a-detiste** [comment]
Please merge https://github.com/twilio/twilio-python/pull/783 first and I will rebase if this can't be done automagicaly with github

**Comment by a-detiste** [comment]
So finally no #783 , I will trim this down

**Comment by tiwarishubham635** [comment]
So there will be some changes in this repo and some in generator repo. We can use #783 for this repo's changes.

**Comment by tiwarishubham635** [comment]
@a-detiste do you want to continue working on it?

**Comment by a-detiste** [comment]
Yes I can

**Comment by a-detiste** [comment]
Well it's done for me... only merge needed

**Comment by tiwarishubham635** [comment]
Please check the failing tests. if mock is part of python since 3.3 then it should work fine with 3.7 as well

**Pull request closed without merging**
