### PR TITLE
chore: drop python<=3.7 support

### PR DESCRIPTION
**Pull request by kloczek**
### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-python/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

### CODE REVIEW

**Comment by tiwarishubham635** [comment]
Is this Python 3.7 has reached its EOL?

**Comment by tiwarishubham635** [comment]
I think you should also remove testing against python 3.7 [here](https://github.com/kloczek/twilio-python/blob/main/.github/workflows/test-and-deploy.yml#L20)

**Comment by a-detiste** [comment]
Do you still want to support 3.7 ? 

https://bugs.python.org/issue45028

**Comment by tiwarishubham635** [comment]
> Do you still want to support 3.7 ?
> 
> https://bugs.python.org/issue45028

I mean we can remove it since its EOL, would need to remove it from test file as well

**Comment by tiwarishubham635** [comment]
As this is an extension of #781, it states:

> According to https://endoflife.date/python python 3.7 is EOSed since 27 Jun 2023.
> Filter all code over pyupgrade --py38.

However, since we want to maintain support for python>=3.8, shouldn't we use the flag `--py38-plus`?

**Comment by kloczek** [comment]
> As this is an extension of #781, it states:
> 
> > According to https://endoflife.date/python python 3.7 is EOSed since 27 Jun 2023.
> > Filter all code over pyupgrade --py38.
> 
> However, since we want to maintain support for python>=3.8, shouldn't we use the flag `--py38-plus`?

It is an mistake in commit comment.
```console
$ pyupgrade --help
usage: pyupgrade [-h] [--exit-zero-even-if-changed] [--keep-percent-format] [--keep-mock] [--keep-runtime-typing] [--py3-plus] [--py36-plus] [--py37-plus] [--py38-plus] [--py39-plus]
                 [--py310-plus] [--py311-plus] [--py312-plus]
                 [filenames ...]

positional arguments:
  filenames

options:
  -h, --help            show this help message and exit
  --exit-zero-even-if-changed
  --keep-percent-format
  --keep-mock
  --keep-runtime-typing
  --py3-plus, --py3-only
  --py36-plus
  --py37-plus
  --py38-plus
  --py39-plus
  --py310-plus
  --py311-plus
  --py312-plus
```

**Comment by kloczek** [comment]
> However, since we want to maintain support for python>=3.8, shouldn't we use the flag `--py38-plus`?

That is exact option which I've used 😋

**Comment by tiwarishubham635** [comment]
Cool. Please remove the python 3.7 from test file and then IO can review.

**Comment by kloczek** [comment]
done

**Comment by tiwarishubham635** [comment]
Hey @kloczek! There are some files in rest folder that are auto generated. For those files to reflect this change, we need to make changes in our generator repo. I'll do the same and update it here. Thanks!

**Comment by tiwarishubham635** [comment]
I have created an [internal ticket](https://issues.corp.twilio.com/browse/DII-1426) for this issue to be fixed. Thanks!

**Comment by tiwarishubham635** [comment]
Closing this as not planned

**Pull request closed without merging**
