### PR TITLE
Remove shipped certs

### PR DESCRIPTION
**Pull request by jingming**

### CODE REVIEW

**Comment by pshafton** [comment]
Don't we still need to provide the path to the CA Bundle even if we use the certifi package. We would need the get_cert_file logic to change to...

import certifi
certifi.where()

**Comment by jingming** [comment]
From my understanding of https://github.com/requests/requests/blob/master/requests/adapters.py#L221 and https://github.com/requests/requests/blob/master/requests/utils.py#L39, I think requests will do this automatically.

**Comment by pshafton** [comment]
Ok. It would be good to verify that behavior. Not sure why our simple test was giving us a warning then.

**Comment by jmctwilio** [comment]
@jingming If you can resolve the conflicts, I think we can mark this as [deploy], yes?

**Comment by jingming** [comment]
@jmctwilio conflicts resolved.

**Pull request merged**
