### PR TITLE
setup.py - stop distributing 'tests'

### PR DESCRIPTION
**Pull request by adamchainz**
Found this hanging around when I installed twilio.

Test Plan: Did `tox -r -e py27`, then `ls .tox/py27/lib/python2.7/site-packages/tests` stopped reporting the directory as existing.

### CODE REVIEW

**Comment by carlosdp** [comment]
:+1:

**Comment by adamchainz** [comment]
I just rebased this.

@jingming please merge this to stop `twilio-python` polluting `site-packages` :)

**Comment by adamchainz** [comment]
rebased, bump @carlosdp

**Comment by adamchainz** [comment]
bump @carlosdp

**Comment by adamchainz** [comment]
rebased, bump @ihumanable @jingming @carlosdp

**Comment by efossier** [comment]
@adamchainz sorry this got ignored for so long. we just released a major redesign of the library in the 6.x series. Is this still a problem?

**Comment by adamchainz** [comment]
Why did you close? This isn't fixed, you can easily tell for yourself by making a new virtualenv, installing `twilio`, then running:

```
$ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tests
>>> tests.holodeck
<module 'tests.holodeck' from '/Users/chainz/.virtualenvs/test/lib/python2.7/site-packages/tests/holodeck.pyc'>
>>>
```

Github has gone crazy on the PR, I think because you've majorly modified the master branch. The only change you need to fix this pollution is my commit, ffcd392203c37efcecb4c8e90dc91a17479ff418 .

**Comment by efossier** [comment]
@adamchainz closed it because it wasnt clear if that was still a problem and this PR was polluted with other commits. I've opened a new pr with just your change it, we'll get it into the next release, thanks for your feedback!

https://github.com/twilio/twilio-python/pull/328

**Pull request closed without merging**
